### ISSUE TITLE
Summary Rows Not Showing Correct Data

### ISSUE THREAD

**Issue by nimeshjain14331** [StefH/KendoGridBinderEx#12]
Hi, I've created a Kendo Grid using KendoGridBinderEx. Thank you for such wonderful work. I have, however, one problem with the Grid. The data at the footer (summary row such as Count and Sum) is not reflecting all the data. It is showing count and sum of the data which is displayed on the current page. For eg, If I have 120 rows and I'm displaying 20 rows per page, then the footer displays count as 20, whereas it should be 120.

Thanks in advance.

**Comment by nimeshjain14331** [comment]
Hi,
Not sure if you've read the message. Please respond if you have.

Thanks,
Nimesh

**Comment by StefH** [comment]
I did send you email to your gmail address.

**Comment by livesoftware** [comment]
Hi StefH,

I was the one talking about the null result set values.  Might have some time this week to dig into it.

**Comment by StefH** [comment]
Hi Mike, maybe we can discuss this via chat (like skype?)

2015-01-05 6:30 GMT+01:00 Mike <notifications@github.com>:

> Hi StefH,
>
> I was the one talking about the null result set values. Might have some
> time this week to dig into it.
>
> Sent from my iPhone
>

**Comment by livesoftware** [comment]
Yeah definitely.   Let me know what's a good time for you this week.




Mike Lonnborg
www.livesoftware.com

 
Date: Sun, 4 Jan 2015 23:08:48 -0800

**Comment by StefH** [comment]
I added support for the serverAggregates, please get the latest from GitHub and do some tests. If this works fine, I'll upload a new Nuget package.

**Comment by StefH** [comment]
NuGet version KendoGridBinderEx.5.0.0.7 uploaded.

**Comment by nimeshjain14331** [comment]
The issue is resolved. Thanks so much.
