### ISSUE TITLE
Filter breaks if the result set contains a null value

### ISSUE THREAD

**Issue by livesoftware** [StefH/KendoGridBinderEx#14]
function loadSearch() {

    var search = document.getElementById('search').value;
    var grid = $("#grid").data("kendoGrid");
    listDataSource._filter = [
        {
            "logic": "or",
            "filters": [
                { field: "LastName", operator: "contains", value: search },
                { field: "FirstName", operator: "contains", value: search }
            ]
        }];
    grid.dataSource.page(1);
    grid.dataSource.read();
}

If the result set contains a null value  "FirstName or LastName" 
var grid = new KendoGridEx<ClassX>(request, list)  crashes
Null Reference Exception

**Comment by sparksterz** [comment]
I've also noticed the same problem...trying to see if there's a way to resolve it without utilizing auto mapper from entities to view models.

**Comment by livesoftware** [comment]
Right that is probably the best way but it would be great to avoid another step.    Also did you notice that by default it sorts by LastName?   It took me forever to realize that.    It would be great if the sortby could be a parameter passed in.  I haven't looked at the code in a month so I'm still a bit foggy.   Would be interested if Ef could be swapped out for Dapper also.

**Comment by sparksterz** [comment]
I actually had not noticed the default sort. I'll have to look back into that. Of importance to note is that this issue only seems to apply to strings. I do not have a problem with null numbers or date values. Trying to map to a type of Nullable<string> doesn't seem to solve the problem either as it's expecting something with a value type. I'll let you know if I find out more.

**Comment by StefH** [comment]
For strings, there is always a ".ToLower()" done. This causes a NullReferenceException when the field is null. I know where this should be fixed, I keep you updated.

**Comment by StefH** [comment]
Issue should be fixed, please test.
NuGet also updated.

**Comment by sparksterz** [comment]
Yep, I see it, we'll test it shortly. We tried a very similar thing in a fork, you just beat us to the punch. Thanks for the quick resolution. I'll validate our scenario against the latest nuget deployment.

**Comment by sparksterz** [comment]
Yeah, it's looking good here. I'll let you know if we encounter any issues, but it doesn't appear to be causing any unintended side-effects.

**Comment by StefH** [comment]
Mike (livesoftware), can you also check please ?
