### ISSUE TITLE
problem in ApplyAggregates when filtering produces zero entities

### ISSUE THREAD

**Issue by kslesinsky** [StefH/KendoGridBinderEx#15]
Hi.  I noticed a problem when applying a filter that didn't match any rows.  It was a "sequence contains no elements" exception in ApplyAggregates(), in the line before the return:

var aggregates = (aggregatesQuery.First() as DynamicClass).GetAggregatesAsDictionary();

...because the evaluation of aggregatesQuery has zero elements.  I would suggest adding a line before that one like:

if (aggregatesQuery.Count() == 0) return null;

My test has two sum aggregates.  I suspect it can be reproduced using the Test_KendoGridModelBinder_Aggregates_WithIncludes() unit test and applying a filter like CompanyName eq "Q".

**Comment by StefH** [comment]
Should be solved, please test with updated nuget package.

**Comment by kslesinsky** [comment]
Hmm, why is there now a dependency on "CreateNewNuGetPackageFromProjectAfterEachBuild"?

**Comment by StefH** [comment]
Good catch. I use this package to create a nuget package, but apperently the new version also includes itself as a dependecy. Funny... I take a look tomorrow.

Grtz.Stef

-----Oorspronkelijk bericht-----
Van: "kslesinsky" <notifications@github.com>
Verzonden: ‎17-‎4-‎2015 23:08
Aan: "StefH/KendoGridBinderEx" <KendoGridBinderEx@noreply.github.com>
CC: "Stef" <Stef.Heyenrath@gmail.com>
Onderwerp: Re: [KendoGridBinderEx] problem in ApplyAggregates when filteringproduces zero entities (#15)

Hmm, why is there now a dependency on "CreateNewNuGetPackageFromProjectAfterEachBuild"?

**Comment by StefH** [comment]
It not related to CreateNewNuGetPackageFromProjectAfterEachBuild 1.8.5.

I did manually remove this dependency from the nuget package.

Please get latest nuget and retest.

**Comment by kslesinsky** [comment]
That works for me.  Thanks!
