### ISSUE TITLE
Unsupported Cast operation with RavenDB

### ISSUE THREAD

**Issue by hanssens** [StefH/KendoGridBinderEx#17]
When trying to use the KendoGridEx with RavenDB (v3.x), I stumble upon a problem with RavenDB not supporting the .Cast() operation.

In short, I've traced down the problem to a crash on the [.Cast method in the GetAutoMapperConversion() function](https://github.com/StefH/KendoGridBinderEx/blob/7ba8011b6b08cc62073491ec4996b951f5cda57f/KendoGridBinderEx/KendoGridEx.cs#L339). 

This results in the following error:

```
Message: "Could not understand expression: .OrderBy(Param_0 => Param_0.Id).Take(50).Cast()"
InnerException: "Method not supported: Cast"
Source: Raven.Client.Lightweight
```

As said, the cause is quite simple: RavenDB doesn't support it deliberately. However, the solution seems to be simple as well. Considering I'm not using AutoMapper to map to a viewmodel, changing the [following line](https://github.com/StefH/KendoGridBinderEx/blob/master/KendoGridBinderEx/KendoGridEx.cs#L90) works beautifully:

```
// This doesn't work, as it calls the .Cast() earlier when _conversion is null
//Data = _conversion(_query).ToList();

// This does work if there's no need for automapper
Data = (IEnumerable<TViewModel>)_query.ToList();
```

This renders the entire GetAutoMapperConversion function obsolete, it seems. 

I would love to prepare a pull request on this one, but am a bit doubting on what would be an ideal - or better - way to prevent this .Cast() problem related to RavenDB. Any thoughts, @StefH?

Thanks.

**Comment by StefH** [comment]
Isn't possible to provide your own "conversion" func in the constructor from KendoGridEx which doesn't do the cast?

**Comment by hanssens** [comment]
Indeed, a good idea. But that would only require an overload on the KendoGridEx<TModel>, right? E.g. the singular version doesn't support it right now:

	// ... no overload
	var grid = new KendoGridEx<Product>(request, products.AsQueryable());

**Comment by StefH** [comment]
Good point. I'll take a look in some detail some in some days.

**Comment by StefH** [comment]
I've added the constructor + extension for TModel.
Please check if you can now use the code (by adding own conversion method).

**Comment by StefH** [comment]
Did you try this code:

```
Func<IQueryable<Employee>, IEnumerable<Employee>> conversion = queryable => queryable.ToList();
var employees = new KendoGridEx<Employee>(request, employees.AsQueryable(), null, null, conversion);
```

With this constructor you can override the default **conversion** function with your own.

**Comment by StefH** [comment]
Did you try this code:

```
Func<IQueryable<Employee>, IEnumerable<Employee>> conversion = queryable => queryable.ToList();
var employees = new KendoGridEx<Employee>(request, employees.AsQueryable(), null, null, conversion);
```

With this constructor you can override the default **conversion** function with your own.

**Comment by StefH** [comment]
@hanssens Closing issue, if you still have a question, please raise a new issue.
