### ISSUE TITLE
Is it free grid control?

### ISSUE THREAD

**Issue by tridipkolkata** [StefH/KendoGridBinderEx#18]
HI,

please tell me is it free grid control?. can we use it in production environment if we download come from here. thanks

**Comment by StefH** [comment]
Yes its free.
Post any questions or remarks to 

-----Oorspronkelijk bericht-----
Van: "tridipkolkata" <notifications@github.com>
Verzonden: ‎15-‎10-‎2015 10:20
Aan: "StefH/KendoGridBinderEx" <KendoGridBinderEx@noreply.github.com>
Onderwerp: [KendoGridBinderEx] Is it free grid control? (#18)

HI,
please tell me is it free grid control?. can we use it in production environment if we download come from here. thanks
