### ISSUE TITLE
Bugs for ASP.NET Core version

### ISSUE THREAD

**Issue by gordon-matt** [StefH/KendoGridBinderEx#20]
Nice work on this.. I've just discovered it today and wish to use it with ASP.NET Core. I've got it working, but not without a bit of hacking it due to some issues:

Firstly, the `KendoGridEx<TEntity>(request, query)` doesn't work. When looking into the code, I discovered it's because it passes null for the `conversion` parameter in the base class' constructor and that causes a Null Reference Exception at line 86, which is:

`Data = _conversion(_query).ToList();`

The other thing is the `KendoGridMvcRequest` was always coming through as null. The model binding wasn't working and it seems this is because you are not using the `KendoGridMvcModelBinder`.. instead your `KendoGridMvcRequest` is simply as follows:

https://github.com/StefH/KendoGridBinderEx/blob/master/KendoGridBinderEx/ModelBinder/Mvc.AspNetCore/KendoGridMvcRequest.cs

```
[ModelBinder]
public class KendoGridMvcRequest : KendoGridBaseRequest
{
}
```
The `ModelBinder` should be specified.

Finally.. last thing to fix is the following... your model binder (mentioned above) needs this line changed:

`return Task.FromResult(kendoGridRequest);`

to this:

```
bindingContext.Result = ModelBindingResult.Success(kendoGridRequest);
return Task.CompletedTask;
```

**Comment by StefH** [comment]
Thanks for reporting this. I'll try to fix these issues. Or you can already make a PR for the things which you can fix?

**Comment by StefH** [comment]
Please check latest NuGet which includes your PR.

**Comment by gordon-matt** [comment]
Looking good. Thanks!
