### ISSUE TITLE
Aggregates,filtering and sorting not working.

### ISSUE THREAD

**Issue by yadavbharat** [StefH/KendoGridBinderEx#23]
Aggregates not working when "serverAggregates" set to true.
Filtering and sorting not working.
Also method "IndexGrouped3" is not working from sample project.

**Comment by StefH** [comment]
The demo project still works : http://kendogridbinderex.apphb.com/Employee/IndexGrouped3 , but that's an older version from the code I guess.

**Comment by StefH** [comment]
Demo fixed, see https://kendogridbinderex.azurewebsites.net/

**Comment by yadavbharat** [comment]
Thanks for reply. Can you upload latest version of "KendoGridBinderEx" on nuget.

**Comment by StefH** [comment]
https://www.nuget.org/packages/KendoGridBinder/2.0.0-preview-1

**Comment by StefH** [comment]
Please note that the namespaces have changed. I removed the "ex".
