### ISSUE TITLE
Unable to obtain the filter values through FilterObjectWrapper

### ISSUE THREAD

**Issue by izhamcheros** [StefH/KendoGridBinderEx#28]
Hi StefH,

I was trying to contact you personally but I have no other options but to write in here. I would like to seek your help in this matter. 

My grid is working. If I applied the filters, the browser seems to process something at the back but in the end, the same result is produced. I have been trying to access the filter and sort object values using FilterObjectWrapper using the below code to access the filter's value, but none of the request.FilterObjectWrapper had value; it is always giving null value. 

```c#
public IEnumerable slaToUse(SlaBaseViewModel slaQueried, KendoGridMvcRequest request)
        {
            SlaBaseViewModel query = slaQueried;
            if (request.FilterObjectWrapper != null)
            {
                IEnumerable filters = (IEnumerable)request.FilterObjectWrapper.FilterObjects.GetEnumerator();
                IEnumerable sorts = (IEnumerable)request.SortObjects.GetEnumerator();
                
                foreach (FilterObject filter in filters)
                {
                    if (filter.Field1 == "SLAName")
                    {
                        query = (SlaBaseViewModel)query.ListOfSlas.Where(x => x.SNCBusinessServices.ServiceName == filter.Value1).Take(10);
                    }
                }
            }
            return query.ListOfSlas;
        }
```
Appreciate your help on this one.

**Comment by StefH** [comment]
If it's a NET Core MVC app, you need this code:
https://github.com/StefH/KendoGridBinderEx/blob/master/examples/WebApplication.NETCore2/Startup.cs#L25

For normal MVC you probably need like this:
https://github.com/StefH/KendoGridBinderEx/blob/master/examples/KendoGridBinderEx.Examples.MVC/Global.asax.cs#L37

**Comment by izhamcheros** [comment]
Hi StefH,

Thanks for your help. I was just able to look at the code today and try it out. Yes, it works like a charm. I was just wondering if even the filters are working without having to program it at the backend?

Thanks a lot

-Izham-

**Comment by StefH** [comment]
Hello Izham; the purpose from this library is that
1. all ui settings like filter, sort, paging and grouping are translated into a object
2. all logic in this object is translated into a dynamic linq code
3. System.Linq.Dynamic.Core library creates the correct SQL statements
4. done
