### ISSUE TITLE
Provide a package for asp.net core > 2 only

### ISSUE THREAD

**Issue by Bjego** [StefH/KendoGridBinderEx#29]

**Comment by Bjego** [comment]
Hey,
could you please refactor your code to use no more preprocessor directives for the .net core 2 / netstandard version of you package? 

Why is this intresting:
I'm devloping a bigger asp.net core mvc application (Framework 2.2), but unfortunally I have to run it on the full framework.
With those preprocessor directives I can't use your .net core classes , the code forces me to use the old asp.net framwork version. But those Modelbinders are incompatible to asp.net core mvc. 
So an extra package for .net core only would be very helpful, **maybe KendoGridBinder.NetCore**.
 
This issue is related to : 
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if 
and to #22

**Comment by StefH** [comment]
Sorry I don't understand your question. Can you maybe create an simple example project on Github and tell me the exact problems?

The package is designed in such a way that it can be used for net45, netstandard1.6 and netstandard2.0

**Comment by Bjego** [comment]
Yeah sure. - I think i can add it next week to this issue. 
Thanks for your reply!

**Comment by Bjego** [comment]
Hey @StefH  I created a sample app:
Here is my project File as you can see - it's an asp.net core application on the full dotnet framework.
https://github.com/Bjego/IssueGridBinderAspNetCoreFullFramework/blob/master/DemoApp/DemoApp.csproj

And the home controller tries to bind the request. But the hardcoded ModelBinder is always a System.Web.Mvc.IModelBinder.
https://github.com/Bjego/IssueGridBinderAspNetCoreFullFramework/blob/master/DemoApp/Controllers/HomeController.cs

**Comment by StefH** [comment]
OK. I will check your project,

**Comment by StefH** [comment]
Preview --> https://www.nuget.org/packages/KendoGridBinder.AspNetCore/3.0.0-preview-01

**Comment by Bjego** [comment]
Hey @StefH , I tried your package in my main application. Your gridbinder is now used, but it crashes, with 
the developer exception page, when my request should be bound.
Could you push your new Branch? So that I can have a quick look what exactly crashes? Maybe I can figure out why the binder crashes. And create a PR for it.

**Comment by Bjego** [comment]
Ah just spotted the branch ... Will have a look what exactly causes the issue

**Comment by StefH** [comment]
That branch does also have your (modified) DemoApp project.

**Comment by Bjego** [comment]
Cool. Let's see how it works with the PR #31

**Comment by StefH** [comment]
Preview-02 is added to NuGet

**Comment by Bjego** [comment]
@StefH yep that works for me this issue has been solved now.
