### ISSUE TITLE
Not able to run Project giving exception for System.Linq.Dynamic.Core

### ISSUE THREAD

**Issue by mayankgaur** [StefH/KendoGridBinderEx#32]
I am having below issue while running your project.
![image](https://user-images.githubusercontent.com/5146368/63913806-0e245500-ca4f-11e9-964a-2bdd642dc7d8.png)

**this same issue occur when I am using your package in my project**. 
Please find image of my code which I have taken reference from your site.

![image](https://user-images.githubusercontent.com/5146368/63914338-7c1d4c00-ca50-11e9-8d0a-13790457d671.png)

![image](https://user-images.githubusercontent.com/5146368/63914363-99521a80-ca50-11e9-8772-e9669157ca26.png)

Nuget Package which I have taken 

![image](https://user-images.githubusercontent.com/5146368/63914444-d9190200-ca50-11e9-89c5-bb2caf81302a.png)

**Comment by mayankgaur** [comment]
@StefH this can be resolve by upgrading the version of System.Linq.Dynamic.Core, to 1.0.18.0. I have resolved this. could you please update your package

**Comment by StefH** [comment]
New NuGets uploaded

**Comment by mayankgaur** [comment]
@StefH Have you updated nuget package also?

**Comment by StefH** [comment]
Yes.
https://www.nuget.org/packages/KendoGridBinder.AspNetCore/3.1.0
