### ISSUE TITLE
Having issue while using server grouping

### ISSUE THREAD

**Issue by mayankgaur** [StefH/KendoGridBinderEx#34]
Steps to produce:-
Add groupable:true to kendoGrid function 
![image](https://user-images.githubusercontent.com/5146368/63930836-b64b1580-ca71-11e9-9e4e-997c09f0e299.png)

then add add serverGrouping: true
![image](https://user-images.githubusercontent.com/5146368/63930874-c82cb880-ca71-11e9-8d38-d3aefe2cb3fb.png)

below is bug details:-
![image](https://user-images.githubusercontent.com/5146368/63930942-ea263b00-ca71-11e9-9885-bdf4e99dbf91.png)

Cause of bug:- Converting TviewModel

![image](https://user-images.githubusercontent.com/5146368/63931030-15a92580-ca72-11e9-8c38-b6884c18a3c9.png)

**Comment by StefH** [comment]
Good point. I'll check.

**Comment by StefH** [comment]
Can you provide the full stack trace?

**Comment by StefH** [comment]
https://github.com/StefH/KendoGridBinderEx/pull/35

**Comment by StefH** [comment]
NuGet 3.2.0 will fix this.
