### ISSUE TITLE
Incompatible with .NET Core 3 / .NET Standard 2.1

### ISSUE THREAD

**Issue by gordon-matt** [StefH/KendoGridBinderEx#38]
I am moving to .NET Core 3.1 and updating all my NuGet packages. This one gives the following error:
**"Restored using '.NETFramework, Version=4.61' instead of the target framework..."**

Could you please release a version targeting .NET Standard 2.1?

**Comment by StefH** [comment]
@gordon-matt Are you using this one?
https://www.nuget.org/packages/KendoGridBinder.AspNetCore

**Comment by gordon-matt** [comment]
Thanks, @StefH . I didn't realize there was a new package.
