### ISSUE TITLE
Question - What is your reasoning to license this library under GPL 3.0?

### ISSUE THREAD

**Issue by maulik-modi** [StefH/KendoGridBinderEx#39]
I believe Kendo grid component is heavily used in **closed source commercial projects** for frontend work, making this library GPL 3.0 makes it unsuitable for those projects. 

I would be happy to know if there are open source projects distributing Kendo source code as part of open source distribution.

LGPL or MIT are better suitable for libraries like KendoGridBinderEx e.g. 
https://github.com/linmasaki/Kendo.DynamicLinqCore
https://github.com/tayyabnasir22/Kendo-JQuery-Grid-Server-Filtering-Sorting-Aggregate-Mapping

**Comment by StefH** [comment]
Hello @maulik-modi , there is not really a reasoning  for that license. This library was based on https://github.com/rwhitmire/KendoGridBinder which I took over from the original author.
And at that time, that library did not have a license I believe. Then I just choose a 'random' opensource license.

And when I look at my file history, I see:
![image](https://user-images.githubusercontent.com/249938/77142762-69687400-6a81-11ea-947d-4c7161b178fa.png)

It seems that I started with MIT, but changed this into GPL3?

(I need to verify why I did that ....)

**Comment by maulik-modi** [comment]
@StefH , have you been recollect your reasoning for moving from MIT -> GPL3?

**Comment by StefH** [comment]
I could not recollect anymore, I'll just move to MIT. (hopefully this is legally allowed...)

**Comment by maulik-modi** [comment]
Yes, MIT is more permissive and encourages more community contribution - those who are using your library in commercial projects.

**Comment by StefH** [comment]
https://github.com/StefH/KendoGridBinderEx/pull/42
